# Generated by Django 2.2.6 on 2019-11-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salery', models.FloatField()),
                ('addr', models.CharField(max_length=50)),
                ('desg', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee_info',
            },
        ),
    ]
